#!/bin/bash

###
# We can't start the autotunnel directly because launchd is uncooperative
# (I can't find a way to fork where autossh keeps running, and if it you
# leave it running autotunnel won't be called again. Boo!)
###

if [[ `networksetup -getsocksfirewallproxy Airport | grep 'Enabled: Yes'` ]]; then
  # Start
  launchctl load -w ~/Library/LaunchAgents/local.autotunnel.autossh.plist
# Thanks Lion!  
elif [[ `networksetup -getsocksfirewallproxy Wi-Fi | grep 'Enabled: Yes'` ]]; then
  # Start
  launchctl load -w ~/Library/LaunchAgents/local.autotunnel.autossh.plist
else
  # Stop
  launchctl unload -w ~/Library/LaunchAgents/local.autotunnel.autossh.plist
fi
